name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.7, 3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: which python
    - name: install conda dependenies
      env:
        TORCH: "1.8"
      run: conda install scipy mpi4py h5py==3.1.0 pytorch==${TORCH} torchvision cpuonly -c pytorch -c conda-forge

    - name: install torch geometric
      env:
        TORCH_GEO: "1.8.0"
      run: |
        pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_GEO}+cpu.html
        pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_GEO}+cpu.html
        pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_GEO}+cpu.html
        pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH_GEO}+cpu.html
        pip install torch-geometric

    - name: Install the package
      run: pip install .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest --cov-config setup.cfg

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
      run: |
        coveralls --service=github


